### ISSUE TITLE
creative work calculation issue

### ISSUE THREAD

**Issue by vitvitvit** [Meosit/poland-taxes-calculator#2]
Hi,

Looks like there is an error in the calculation of the creative work quota.
In logs, it shows the formula like (if set salary = 10000, creative work 55%):

`> You have a PIT base reduce due to creative work quota by 55%: 8629 * 55 / 100 = 4745.95 (with a maximum of 120000, currently is 0)`

After that you just decrease the second tax base for this amount:

```
> For PIT, there is a fixed locality tax free amount of 250 (since you're living in the city where you're working).
--
> So, the base for the PIT is: 8629 - 4745.95 - 250 = 3633.05
```

As I understand (from articles on the internet and as my payslip provider does), you need to multiply 4745.95 by 50%. As I understand creative work % applies to 50% of the tax base.
So the calculation, in this case, will be:

8629 *50/100 * 55 / 100 = 2372.97
8629 - 2372.97 - 250 = 6006.03
6006.03 * 12 / 100 = 720.7

BTW, thanks for the calculator

**Comment by Meosit** [comment]
Seems to be a bug, even with correct description of the field. Fixed. Please check on your side if possible

**Comment by vitvitvit** [comment]
this point looks right now, thanks
